### PR TITLE
Multiple improvements listed below

### LINKED ISSUE #22: ultipro_google fails with "element not interactable"
When I use ultipro_google, it logs in properly but crashes with:

```
[0/1] google_payroll [41s elapsed] 2019-09-27 21:17:23,347 ultipro_google.py:144 [INFO] Document datetime.date(2019, 9, 26) : 'UA29063061':  Downloading
[0/1] google_payroll [42s elapsed] Traceback (most recent call last):
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/finance_dl/scrape_lib.py", line 402, in retry
[0/1] google_payroll [42s elapsed]     return func()
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/finance_dl/scrape_lib.py", line 422, in fetch
[0/1] google_payroll [42s elapsed]     scraper.run()
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/finance_dl/ultipro_google.py", line 206, in run
[0/1] google_payroll [42s elapsed]     self.download_statements()
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/finance_dl/ultipro_google.py", line 200, in download_statements
[0/1] google_payroll [42s elapsed]     downloaded_statements=downloaded_statements,
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/finance_dl/ultipro_google.py", line 152, in get_next_statement
[0/1] google_payroll [42s elapsed]     download_link.click()
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
[0/1] google_payroll [42s elapsed]     self._execute(Command.CLICK_ELEMENT)
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
[0/1] google_payroll [42s elapsed]     return self._parent.execute(command, params)
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
[0/1] google_payroll [42s elapsed]     self.error_handler.check_response(response)
[0/1] google_payroll [42s elapsed]   File "/home/mark/p/finances/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
[0/1] google_payroll [42s elapsed]     raise exception_class(message, screen, stacktrace)
[0/1] google_payroll [42s elapsed] selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
[0/1] google_payroll [42s elapsed]   (Session info: chrome=77.0.3865.90)
```

### PR DESCRIPTION
**Pull request by jktomer**
- pge: write temp files with .pdf extension (formerly #51)
- pass overwrite flag to atomic_write (formerly #56)
- utlipro: wait for page to load when clicking download link (formerly #63) (fixes #22)

### CODE REVIEW

**Comment by jktomer** [comment]
Failures are odd, look like some problem with the test environment setup? Am I able to rerun them myself?

**Comment by Zburatorul** [comment]
Yeah I don't understand the mypy cache folder issue. I deleted mine but mypy still succeeded.

I don't see a way to approve you for automatic builds.

**Comment by Zburatorul** [comment]
@jbms, you might have a better idea how the testing environment is set up, and why `mypy` is suddenly failing.
Seems related to [this issue](https://github.com/python/mypy/issues/10863). 

I have the same mypy version and for me `mypy --install-types --non-interactive finance_dl` succeeds even when the cache folder is missing.

**Comment by Zburatorul** [comment]
@jktomer, the build should succeed now after a rebase.

**Comment by jktomer** [comment]
Aha—it doesn't pass, but it does fail more interestingly!

Fixed; I have no idea why it passes on my machine...

**Comment by jktomer** [comment]
mergeable now I think?

**Review by Zburatorul — APPROVED** [review]

**Pull request merged**
