### PR TITLE
Make scraper for Amazon work with amazon.de.

### PR DESCRIPTION
**Pull request by Marvin182**
Tested with my account on amazon.de.
There is probably a solution that doesn't require us to hardcode country specific strings but it would be more work.

### CODE REVIEW

**Comment by Zburatorul** [comment]
Looks good. 
I tried it and it works for me, except on Amazon Fresh orders. 
Note that master also fails on Amazon Fresh orders and there's already a small PR out to fix that. Let's give that a chance to get merged first.

**Comment by Marvin182** [comment]
Sounds good.

**Comment by Zburatorul** [comment]
@Marvin182, we're now ready for this PR. Looks like the last one introduced a small conflict. Can you have a look at resolve it please?

**Comment by Marvin182** [comment]
Done, but I currently don't have access to my Amazon account to test it. I also don't use Amazon fresh.

**Comment by Marvin182** [comment]
Sorry, I messed up and created a new pull request with the squashed changes.

**Pull request closed without merging**
